import type { Category, Intent, ParsedAction, ParsedCommand } from "@/domain/command";
import type { Product, Season } from "@/domain/product";
import type { ListItem, Activity, PurchaseHistoryRecord } from "@/domain/shopping";
import type { Suggestion, RecommendationKind } from "@/domain/recommendation";

export type {
  Category,
  Intent,
  ParsedAction,
  ParsedCommand,
  Product,
  Season,
  ListItem,
  Activity,
  PurchaseHistoryRecord,
  Suggestion,
  RecommendationKind,
};

export const CATEGORIES: Category[] = [
  "Dairy",
  "Produce",
  "Bakery",
  "Snacks",
  "Personal Care",
  "Beverages",
  "Pantry",
  "Other",
];

export const PRODUCTS: Product[] = [
  // Dairy
  {
    id: "p-milk",
    name: "Milk",
    brand: "Amul",
    category: "Dairy",
    price: 68,
    size: "1 L",
    unit: "bottles",
    organic: false,
    season: "all",
    available: true,
    substitutes: ["p-almond-milk", "p-soy-milk"],
    popular: true,
    aliases: ["milk", "doodh", "dudh", "दूध"],
  },
  {
    id: "p-almond-milk",
    name: "Almond Milk",
    brand: "Raw Pressery",
    category: "Dairy",
    price: 189,
    size: "1 L",
    unit: "cartons",
    organic: true,
    season: "all",
    available: true,
    substitutes: ["p-milk"],
    aliases: ["almond milk", "badam milk"],
  },
  {
    id: "p-soy-milk",
    name: "Soy Milk",
    brand: "Sofit",
    category: "Dairy",
    price: 145,
    size: "1 L",
    unit: "cartons",
    organic: false,
    season: "all",
    available: true,
    substitutes: ["p-milk"],
    aliases: ["soy milk", "soya milk"],
  },
  {
    id: "p-cheese",
    name: "Cheese",
    brand: "Go",
    category: "Dairy",
    price: 235,
    size: "200 g",
    unit: "packs",
    organic: false,
    season: "all",
    available: true,
    aliases: ["cheese", "cheddar", "paneer"],
  },
  {
    id: "p-butter",
    name: "Butter",
    brand: "Amul",
    category: "Dairy",
    price: 58,
    size: "100 g",
    unit: "packs",
    organic: false,
    season: "all",
    available: true,
    aliases: ["butter", "makhan", "makkhan"],
  },
  {
    id: "p-yogurt",
    name: "Yogurt",
    brand: "Epigamia",
    category: "Dairy",
    price: 55,
    size: "90 g",
    unit: "cups",
    organic: false,
    season: "all",
    available: true,
    aliases: ["yogurt", "curd", "dahi"],
  },

  // Produce
  {
    id: "p-apples",
    name: "Apples",
    brand: "NatureFresh",
    category: "Produce",
    price: 179,
    size: "1 kg",
    unit: "pieces",
    organic: true,
    season: "winter",
    available: true,
    popular: true,
    aliases: ["apple", "apples", "seb", "सेब"],
  },
  {
    id: "p-apples-ff",
    name: "Organic Apples",
    brand: "FreshFarm",
    category: "Produce",
    price: 195,
    size: "1 kg",
    unit: "pieces",
    organic: true,
    season: "winter",
    available: true,
    aliases: ["organic apples", "organic seb"],
  },
  {
    id: "p-apples-basic",
    name: "Apples",
    brand: "Local Market",
    category: "Produce",
    price: 129,
    size: "1 kg",
    unit: "pieces",
    organic: false,
    season: "winter",
    available: true,
  },
  {
    id: "p-bananas",
    name: "Bananas",
    brand: "Farm Direct",
    category: "Produce",
    price: 54,
    size: "6 pcs",
    unit: "bunch",
    organic: false,
    season: "all",
    available: true,
    popular: true,
    aliases: ["banana", "bananas", "kela", "केला"],
  },
  {
    id: "p-mangoes",
    name: "Mangoes",
    brand: "Ratnagiri Farms",
    category: "Produce",
    price: 320,
    size: "1 kg",
    unit: "kg",
    organic: true,
    season: "summer",
    available: true,
    popular: true,
    aliases: ["mango", "mangoes", "aam", "आम"],
  },
  {
    id: "p-oranges",
    name: "Oranges",
    brand: "Nagpur Grove",
    category: "Produce",
    price: 110,
    size: "1 kg",
    unit: "kg",
    organic: false,
    season: "winter",
    available: true,
    aliases: ["orange", "oranges", "santra", "संतरा"],
  },
  {
    id: "p-tomatoes",
    name: "Tomatoes",
    brand: "FreshFarm",
    category: "Produce",
    price: 42,
    size: "500 g",
    unit: "kg",
    organic: false,
    season: "all",
    available: true,
    aliases: ["tomato", "tomatoes", "tamatar", "टमाटर"],
  },
  {
    id: "p-potatoes",
    name: "Potatoes",
    brand: "Local Market",
    category: "Produce",
    price: 38,
    size: "1 kg",
    unit: "kg",
    organic: false,
    season: "all",
    available: false,
    aliases: ["potato", "potatoes", "aloo", "aalu", "आलू"],
  },

  // Bakery
  {
    id: "p-bread",
    name: "Bread",
    brand: "Britannia",
    category: "Bakery",
    price: 45,
    size: "400 g",
    unit: "loaf",
    organic: false,
    season: "all",
    available: true,
    substitutes: ["p-multigrain-bread"],
    aliases: ["bread", "ब्रेड", "पाव"],
  },
  {
    id: "p-multigrain-bread",
    name: "Multigrain Bread",
    brand: "The Baker's Dozen",
    category: "Bakery",
    price: 95,
    size: "400 g",
    unit: "loaf",
    organic: true,
    season: "all",
    available: true,
    substitutes: ["p-bread"],
    aliases: ["multigrain bread", "brown bread"],
  },

  // Snacks
  {
    id: "p-chips",
    name: "Chips",
    brand: "Lay's",
    category: "Snacks",
    price: 30,
    size: "52 g",
    unit: "packs",
    organic: false,
    season: "all",
    available: true,
    aliases: ["chips", "potato chips", "चिप्स"],
  },
  {
    id: "p-biscuits",
    name: "Biscuits",
    brand: "Parle",
    category: "Snacks",
    price: 25,
    size: "250 g",
    unit: "packs",
    organic: false,
    season: "all",
    available: true,
    aliases: ["biscuit", "biscuits", "parle-g", "बिस्कुट"],
  },

  // Personal Care
  {
    id: "p-toothpaste",
    name: "Toothpaste",
    brand: "Colgate",
    category: "Personal Care",
    price: 99,
    size: "150 g",
    unit: "tubes",
    organic: false,
    season: "all",
    available: true,
    substitutes: ["p-toothpaste-herbal"],
    aliases: ["toothpaste", "colgate", "टूथपेस्ट"],
  },
  {
    id: "p-toothpaste-herbal",
    name: "Herbal Toothpaste",
    brand: "Dabur",
    category: "Personal Care",
    price: 145,
    size: "200 g",
    unit: "tubes",
    organic: true,
    season: "all",
    available: true,
    aliases: ["herbal toothpaste", "dabur red"],
  },
  {
    id: "p-shampoo",
    name: "Shampoo",
    brand: "Dove",
    category: "Personal Care",
    price: 265,
    size: "340 ml",
    unit: "bottles",
    organic: false,
    season: "all",
    available: true,
    aliases: ["shampoo", "dove shampoo", "शैम्पू"],
  },
];

export const productById = (id: string): Product | undefined => PRODUCTS.find((p) => p.id === id);

export function findProductByName(name: string): Product | undefined {
  const q = name.trim().toLowerCase();
  return (
    PRODUCTS.find((p) => p.name.toLowerCase() === q) ??
    PRODUCTS.find((p) => p.aliases?.some((a) => a.toLowerCase() === q)) ??
    PRODUCTS.find((p) => p.name.toLowerCase().includes(q)) ??
    PRODUCTS.find((p) => p.aliases?.some((a) => a.toLowerCase().includes(q)))
  );
}

export const INITIAL_LIST: ListItem[] = [
  {
    id: "l1",
    name: "Milk",
    category: "Dairy",
    quantity: 2,
    unit: "bottles",
    done: false,
    addedAt: Date.now() - 1000 * 60 * 60,
    updatedAt: Date.now() - 1000 * 60 * 60,
  },
  {
    id: "l2",
    name: "Cheese",
    category: "Dairy",
    quantity: 1,
    unit: "pack",
    done: true,
    addedAt: Date.now() - 1000 * 60 * 120,
    updatedAt: Date.now() - 1000 * 60 * 30,
  },
  {
    id: "l3",
    name: "Apples",
    category: "Produce",
    quantity: 5,
    unit: "pieces",
    done: false,
    addedAt: Date.now() - 1000 * 60 * 90,
    updatedAt: Date.now() - 1000 * 60 * 90,
  },
  {
    id: "l4",
    name: "Bananas",
    category: "Produce",
    quantity: 1,
    unit: "bunch",
    done: false,
    addedAt: Date.now() - 1000 * 60 * 45,
    updatedAt: Date.now() - 1000 * 60 * 45,
  },
  {
    id: "l5",
    name: "Tomatoes",
    category: "Produce",
    quantity: 1,
    unit: "kg",
    done: true,
    addedAt: Date.now() - 1000 * 60 * 180,
    updatedAt: Date.now() - 1000 * 60 * 10,
  },
  {
    id: "l6",
    name: "Bread",
    category: "Bakery",
    quantity: 1,
    unit: "loaf",
    done: false,
    addedAt: Date.now() - 1000 * 60 * 200,
    updatedAt: Date.now() - 1000 * 60 * 200,
  },
  {
    id: "l7",
    name: "Biscuits",
    category: "Snacks",
    quantity: 2,
    unit: "packs",
    done: true,
    addedAt: Date.now() - 1000 * 60 * 240,
    updatedAt: Date.now() - 1000 * 60 * 15,
  },
  {
    id: "l8",
    name: "Toothpaste",
    category: "Personal Care",
    quantity: 1,
    unit: "tube",
    done: false,
    addedAt: Date.now() - 1000 * 60 * 300,
    updatedAt: Date.now() - 1000 * 60 * 300,
  },
];

export const INITIAL_PURCHASE_HISTORY: PurchaseHistoryRecord[] = [
  {
    id: "h1",
    productName: "Milk",
    category: "Dairy",
    quantity: 2,
    unit: "bottles",
    timestamp: Date.now() - 1000 * 60 * 60 * 24 * 8, // 8 days ago
  },
  {
    id: "h2",
    productName: "Milk",
    category: "Dairy",
    quantity: 2,
    unit: "bottles",
    timestamp: Date.now() - 1000 * 60 * 60 * 24 * 15, // 15 days ago
  },
  {
    id: "h3",
    productName: "Bread",
    category: "Bakery",
    quantity: 1,
    unit: "loaf",
    timestamp: Date.now() - 1000 * 60 * 60 * 24 * 5,
  },
];

export const SUGGESTIONS: Suggestion[] = [
  {
    id: "s1",
    kind: "habit",
    productId: "p-milk",
    title: "Milk",
    line1: "You usually buy this every 7 days.",
    line2: "Last purchased 8 days ago.",
    cta: "add",
  },
  {
    id: "s2",
    kind: "seasonal",
    productId: "p-mangoes",
    title: "Mangoes",
    line1: "Popular this season",
    line2: "Peak seasonal harvest right now.",
    cta: "add",
  },
  {
    id: "s3",
    kind: "substitute",
    productId: "p-almond-milk",
    title: "Almond Milk",
    line1: "An alternative to Milk",
    line2: "Lactose-free · 2 options nearby",
    cta: "options",
  },
];

export const SEARCH_FILTERS = [
  "All",
  "Organic",
  "Under ₹200",
  "Popular",
  "Best Match",
  "Price: Low to High",
] as const;

export type SearchFilter = (typeof SEARCH_FILTERS)[number];

export const VOICE_EXAMPLES = [
  "Add 2 bottles of milk",
  "Remove bread",
  "Find toothpaste under ₹200",
  "What should I buy?",
];
